### ISSUE TITLE
Promeniti tekst "ostavi me prijavljenog" u neutralan rod

### ISSUE THREAD

**Issue by teosarkic** [Petlja/bugs-and-improvements#12]
![image](https://cloud.githubusercontent.com/assets/1322239/22405060/d27ec2c2-e63c-11e6-9641-8ee87c39b008.png)

**Comment by delta003** [comment]
Hmmm, mozda "zapamti me"? @teosarkic imas neki bolji predlog?

**Comment by teosarkic** [comment]
Moze.

**Comment by DemjanGrubic** [comment]
Mozda prvo slovo da bude veliko?

**Comment by delta003** [comment]
Ispravljeno na takprog

**Comment by delta003** [comment]
Done
