### ISSUE TITLE
Skloniti obaveznu potvrdu email-a

### ISSUE THREAD

**Issue by delta003** [Petlja/bugs-and-improvements#18]
Trenutno, korisnik ne moze da se uloguje pre nego sto potvrdi email. Mislim da ovo treba skloniti

**Comment by igr** [comment]
2 predloga:

1. dozvoliti mu da se prijavi, sa velikim znakom da mora da se potvrdi
2. ne dozvoliti i objasniti da je biti da se potvrdi.

Ukoliko su korisnici i naši vrli učitelji, predlažem broj 1, pošto njihovo snalaženje nije na velikom nivou.
