### ISSUE TITLE
Omoguciti promenu username-a

### ISSUE THREAD

**Issue by delta003** [Petlja/bugs-and-improvements#19]
Izgleda da su neki korisnici morali da imaju odredjene username-ove na BB, mg_ nesto. Dobili smo molbu da im se promeni username. Predlazem da omogucimo promenu username-a, ali ogranicen broj puta, ili jednom u par meseci ili tako nesto

**Comment by igr** [comment]
ma omogucite beskonacni broj promena, ne zamarajte se s trivijama oko korisničkih imena. Ako se nekom menja, neka menja ;)

**Comment by teosarkic** [comment]
Prebaceno u interni dokument.
