### ISSUE TITLE
Dodati na glavnu stranu petlja.org vesti

### ISSUE THREAD

**Issue by teosarkic** [Petlja/bugs-and-improvements#2]
Vesti mogu da budu iz BubbleBee baze, tako da za sad lako kroz CMS mozemo da ih postavljamo direktno i na petlja.org i na http://bubblebee.petlja.org/vesti (ionako su nam to sve trenutno iste vesti).

**Comment by delta003** [comment]
Bice dodato

**Comment by delta003** [comment]
Pratimo u drugom repou
