### ISSUE TITLE
NaN greska

### ISSUE THREAD

**Issue by kidsmart** [Petlja/bugs-and-improvements#20]
Kada niko nije pokušao da reši zadatak, onda  prilikom deljenja sa nulom dobija se NaN, umesto toga može da stoji crtica.
![](http://image.prntscr.com/image/a849a6027cba4b3f8a71849b4cfe46c3.png)

**Comment by delta003** [comment]
Trenutno radimo na novoj verziji statistike (i celog BubbleBee-a), pa ce ovi biti sredjeno. Hvala!
