### ISSUE TITLE
problem sa statusom rešenja

### ISSUE THREAD

**Issue by kidsmart** [Petlja/bugs-and-improvements#21]
kada pogledam u kod stranice, izgleda da  se  `.test_case` ugnježdava jedan u drugi, tj. da vam fali jedan `</div>` tag u  funkciji createPopup u petlji koja stvara `.test_case`
![](http://image.prntscr.com/image/cdc674c88e4b409f97cd668465803aa1.png)

**Comment by srdjan-bozovic** [comment]
u pravu ste. popravljeno je sada.
