### ISSUE TITLE
PSI:ML Godina Rodjenja

### ISSUE THREAD

**Issue by IlicMiljan** [Petlja/bugs-and-improvements#23]
Na PSI:ML sajtu kod prijave zainteresovanih ucesnika nije moguce odabrati godinu rodjenja za osobe rodjenje posle 1999.

**Comment by kidsmart** [comment]
Mogu li da se prijave srednjoškolci? Pošto sam pročitao da se fokusirate na studente.

**Comment by BubbleBeeSRB** [comment]
@kidsmart Ovo je seminar namenjen studentima, za srednjoškolce Petnica nudi druge seminare, više informacija imaš na http://petnica.rs/index.php?option=com_content&view=article&id=33&Itemid=43 Na seminaru Primenjene Fizike i Elektronike (http://ele.petnica.rs/) se takođe rade projekti iz oblasti Machine Learning-a, i čak je veoma slična grupa saradnika na tom seminaru sa ML seminarom.

**Comment by IlicMiljan** [comment]
http://petnica.rs/index.php?option=com_content&view=article&id=33&Itemid=43

Threat found
**This web page contains potentially dangerous content.**
Threat: HTML/SEOSpam.A trojan
**Access to it has been blocked. Your computer is safe.**

http://ele.petnica.rs/
**This web page contains potentially dangerous content.**
Threat: JS/TrojanDownloader.FakejQuery.B trojan
**Access to it has been blocked. Your computer is safe.**

**Comment by teosarkic** [comment]
@IlicMiljan Hvala na javljanju ovih problema. Gledamo o cemu se radi za ele.petnica.rs a za petnica.rs nismo nadlezni. Javimo kad vidimo o cemu se radi. Da li postoji slican problem na http://psiml.petnica.rs/?

**Comment by IlicMiljan** [comment]
Na http://psiml.petnica.rs/ nema problema.

**Comment by teosarkic** [comment]
@IlicMiljan ocistili smo ele.petnica.rs pa ajd molim te probaj ponovo kad stignes :) Hvala!

**Comment by IlicMiljan** [comment]
Sada nema problema. Inace, skenirano je ESET-om, puna verzija.

**Comment by teosarkic** [comment]
@IlicMiljan super, hvala!
