### ISSUE TITLE
Preostalo vreme u tak. okruzenju se prikazuje na osnovu vremena racunara, a ne servera

### ISSUE THREAD

**Issue by mlosh** [Petlja/bugs-and-improvements#24]
Променом локалног времена још увек може да се користи део предвиђен за квалификације 2016

**Comment by DuXXuD** [comment]
Na šta tačno misliš? Kvalifikacije 2016 nisu na petlja takmičenjima, dok za ovu godinu kvalifikacije traju do danas do 18h.

**Comment by Mill0s** [comment]
![image](https://cloud.githubusercontent.com/assets/13847095/23341499/c0415440-fc16-11e6-81cf-9c934447f7f6.png)

**Comment by DuXXuD** [comment]
Aha, lokalna promena vremena utiče samo na lokalno prikazivanje vremena :) Odnosno na timebar, i očigledno poruku kada timebar stigne do kraja.
Moglo bi da se ispravi s tim da ovde odbrojava vreme u nazad pa može da dođe do zabune ako je nekome podešeno pogrešno vreme.

**Comment by delta003** [comment]
Premesteno
