### ISSUE TITLE
dodajte test primer i resenje

### ISSUE THREAD

**Issue by kidsmart** [Petlja/bugs-and-improvements#25]
![](http://image.prntscr.com/image/6c6dee4f336648e0a93d2166eaf72a16.png)
Možete li da dodate link ka test primeru i rešenju test primera kao na sl., kako bi se lakše mogao proveriti zadatak.
Pitam zato što za jedan zadatak dobijam TLE na 3. i 4. testu, a kada probam na mom računaru dobijam  TLE na 11. i 12. testu(logičnije je da dobijem TLE na testu pod većim rednim brojem), pa mi se čini kao da ste negde obrnuli redosled testova, tj. da je 3. test u stvari 12. a 4. test 11.

**Comment by delta003** [comment]
@kidsmart Pretpostavljam da se radi o nekom problemu sa kvalifikacija i izvinjavam se na ovako kasnom odgovoru.
Moguce je redosled primera u okruzenju nije odgovarao redosledu primera koji je objavila komisija. Ako je tako, to je bila greska.
Sto se tice tvog komentara "logičnije je da dobijem TLE na testu pod većim rednim brojem", nigde u pravilniku se ne pominje redosled test primera, ali slazem se da je logicnije :)
Sto se tice linka ka test primeru, to ne planiramo da uradimo. Takmicarsko okruzenje se pravi kako bi podrzalo razna takmicenja, ne samo takmicenja za srednje skole. Na organizatoru takmicenja je da, ako zeli, objavi test primere.
