### ISSUE TITLE
Nedostaje vam spejs u confirmation emailu

### ISSUE THREAD

**Issue by igr** [Petlja/bugs-and-improvements#26]
![image](https://cloud.githubusercontent.com/assets/2280001/25430813/68964bf6-2a7e-11e7-9495-9e7630a9d645.png)

Zbog ovoga link ne radi.

**Comment by igr** [comment]
I slobodno ne morate ceo link da ispišete u tekstu poruke, već je napravite da bude u HTML formatu i stavite dugme.

**Comment by delta003** [comment]
Fixed
