### ISSUE TITLE
Nije jasno sa sajta o čemu se radi u petlji.

### ISSUE THREAD

**Issue by igr** [Petlja/bugs-and-improvements#27]
Ako je fokus platforma, onda je ok; to je tek još jedna platforma koja se pokušava uključiti u "formalni" obrazovani sistem; te se bori za svoje mesto pod suncem (i finansijama).

Ako je fokus nešto više od platforme, i suštinsko rešavanje problema, onda sajt mora mnogo više da pruži i odgovori. Nije jasno koji se tačno problemi rešavaju, a ni kako. Dalje, koliko je otvorena za uključenje spoljnih ljudi koji NISU direktno iz firmi koje stoje iza petlje? Itd.

Podelio bih odmahi  moja viđenja i neke aktivnosti, pa budite slobodni da me kontaktirate:

https://docs.google.com/document/d/1xMexai67st1QGkrrjaGb1nnpcQfkQ6LxnhmN8dlCU1g/edit?usp=sharing
http://heapspace.rs/kids/

Toliko, hvala.

**Comment by teosarkic** [comment]
Hvala na komentaru i javljanju!

Da, svesni smo ovog problema da nije najjasnije ljudima o cemu se tu zapravo radi. U procesu smo konsolidacije i integracije BubbleBee-ja i Takprog-a u zajednicki sistem. Probacemo ovo da popravimo i da razjasnimo o cemu se radi. Evo na primer koji su problemi u pitanju http://bubblebee.petlja.org/kursevi/Zbirka

Namera nam je da imamo otvorenu platformu i da mozemo da ukljucimo sve koji zele da doprinesu, i delove sistema zelimo da open source-ujemo (ako ne i ceo sistem). Tako da smo otvoreni za sve koji se ovim istim stvarima bave, ne zelimo nikako da se ogranicimo na institucije koje (trenutno) podrzavaju rad Petlje.

Hvala na ovim linkovima, pregledacemo :)
Evo slicnih razmisljanja sa nase strane http://elib.mi.sanu.ac.rs/files/journals/nm/251/nmn251p19-31.pdf

**Comment by igr** [comment]
@teosarkic hvala na dogovoru. imati platformu je u redu, no bojim se da kod nas nije dovoljno. Platforma kao takva je samo nosač sadržaja; iskreno; svašta nešto dostupno može već da posluži na manje/više sličan način.

Pitanje: da li se ovde bavite samo platformom kao softverskim rešenjem; ili se bavite i sadržajem koji se tamo nalazi? Gde mogu da uputim konstruktivne kritike za sam sadržaj?

Pitanje: da li postoji nekakav plan i definicija sadržaja koji bi mogao da bude oblik formalnog obrazovanja? Da li je ta vizija u petlji?

Izvinite što sam dosadan, ali ovime se bavim već dugo bavim, i prilično me žulja sve što se (ne) dešava oko ovoga.

**Comment by teosarkic** [comment]
@igr radimo i na sadrzaju i na platformi. Trenutno imamo preko 900 algoritamskih zadataka, koji su uglavnom grupisani po kursevima. Imamo [Zbirku ](http://bubblebee.petlja.org/kursevi/Zbirka)(bez lekcija) koja predstavlja koncepte i zadatke koje predlazemo da se obrade u prve dve godine ucenja algoritmike, za sad je gotov sadrzaj za prvu godinu ucenja a nastavljamo sa radimo za drugu godinu. Zbirka tematski pokriva program takmičenja iz programiranja za osnovnu školu koje organizuje Društvo matematičara Srbije do naprednih tehnika programiranja, uključujuće samo neke napredne tehnike, a Zbirku mogu da koriste učenici svih uzrasta (počevši od 5. razreda osnovne škole) koji počinju da se pripremaju za takmičenje iz programiranja, a nemaju značajno programersko predznanje. Dakle, ciljna grupa Zbirke su učenici srednjih škola u kojima se programiranje izučava po specijalizovanim planovima i programima, učenici trećeg razreda običnih gimnazija, takmičari osnovci, svi početnici zainteresovani za algoritamsko programiranje.

Imamo i [Prirucnik za pocetnike ](http://bubblebee.petlja.org/Courses/Cpp-za-pocetnike) za C++ a spremna je ali ne i objavljena C# varijanta. Prirucnik je kurs programiranja namenjen pre svega apsolutnim početnicima, ali i svima koji žele da obnove ili upotpune svoje razumevanje osnovnih pojmova u programiranju. Ne očekuje se nikakvo predznanje. Posebna pažnja u kursu je posvećena metodama traženja i ispravljanja grešaka u programu. 

Pored ovih kurseva imamo jos par kurseva kao i dobar deo zadataka sa domacih takmicenja iz prethodnih godina za osnovce i srednjoskolce. Inace Petlja se koristi od ove godine kao platforma za zvanicna takmicenja koja organizuje Drusto Matematicara Srbije. Evo na primer kako to online izgleda, sa zadacima sa okruznog za osnovce ove godine http://petlja.org/Competitions/Competition/18

**Comment by igr** [comment]
@teosarkic ne bih da me pogrešno razumete; disktovati na ovakav način ima svojih ograničenja. smatram da količina materijala nije presudna. Zbirke su tek tekstovi sa slikama. To se ne može zvati platformom. 

Nisam uspeo da se ulogujem u sistem, ali evo nekih funkcionalnosti koje smatram da bi _platforma_ trebalo da ima, bez određenog redosleda:

+ jasna kvalifikacija sadržaja po uzrastu. ili bar nivo kompleksnosti
+ sadržaj na sajtu mora biti jasniji. Bez skeumorfa (sveska, linije...), povećati čitljivost fontova (izabrani font i veličina na uobičajenom laptop monitoru predstavljaju problem deci koja slabije vide), mora da postoji laka mogućnost povećanja/smanjenja fonta; kao i opcija sa ograničenim bojama za deca koja imaju i takve probleme (postoji čitav standard).
+ online pokretanje programa. ne znam da li ovo imate, ali online editor i pokretanje programa je obavezno za platformu. ne možete očekivati da deca koriste `gcc` iz komandne linije :) Ovo je vrlo važno, pošto se pokazalo da 70% dece ima velikih problema upravo jer zbog kompleksnosti okruženja. Zato treba jednostavan online editor i veliko dugme "Pokreni". Danas sa dockerom je to zaista jednostavno implementirati.
+ Sadržaj lekcija ima nula interakcije. Izgleda kao knjiga. Ne koristi se internet i mogućnost interakcije. A znamo da je to jedan od najboljih načina kako se može učiti. Jedna lekcija/tema bi mogla biti podeljena u više celina, a iza svake da ide mini kviz kako bi se naučilo prethodno.
+ Gejmifikacija - ne znam da li imate, ali ovo je obavezno ponuditi.
+ Suvoparnost - predlažem da pogledate bilo koju knjigu iz Head First serijala. Molim vas, nije dovoljno samo da sadržaj bude koncizan, tačan i da ga ima puno. Mora da drži pažnju. Mora da koristi sve trikove koje ljudski mozak ima da bi se lakše i bolje zapamtilo. Ne kažem da je lako, ali za početak možete da ubacite za svaku temu 1-2 crtana lika, sa kojim se deca mogu identifikovati. Primeri takođe da budu što zanimljiviji - evo iskustva iz jedne domaće škole programiranja: deca se uče algoritmima na primeru "izdvoji najveću cifru trocifrenog broja" i "da li je broj deljiv sa.."; klinci su imali problema da shvate uopšte šta je zadatak, a ne da napišu algoritam!
+ Da li je neko od pedagoga uključen u program? Da li imate nekoga sa iskustvom o obuci dece?

Ne zaboravite, platforma nije nešto što samo nudi sadržaj, već mora da _pomogne_ deci da nauče što bolje i kvalitetnije.

Ovo pišem ovde samo jer želim da pomognem, a ne da kritikujem. Tu sam (ujedno ispred zajednice i organizacije [heapspace](http://heapspace.rs)) da pomognem ako budete smatrali da mogu. Užasnut sam i uplašen stanjem IT u školama i to mi ne dozvoljava da mirno spavam.

Zatvoriću ovaj issue sada. Puno sreće u daljem radu; budite slobodni da me kontaktirate ukoliko zatreba.

**Comment by igr** [comment]
Još jednu ideju da podelim od ranije: osmisliti format i standard za lekcije, koje bi se pisale u na pr. _markdown_ i onda se od njih generisao sadržaj na sajtu. Lekcije bi bile postavljene na github i svako bi mogao da ih koristi, dopuni, i sl.

Ovo je jako moćan koncept, koji je tehnološki jednostavan.

I još nešto: pod kojom licencom su objavljeni podaci tj. sadržaj - nisam siguran da sam uhvatio to na sajtu, a smatram da je jako bitno danas. U tu svrhu vredi objaviti sadržaj pod nekom licencom koja je kompatibilna sa [open data](http://opendefinition.org/od/2.1/sr/) licencom.

**Comment by delta003** [comment]
@igr Slazemo se sa idejom i po tom principu se prave sve nove lekcije. Potrebno je jos stare lekcije sa BubbleBee-a prebaciti u odgovarajuci format.

**Comment by teosarkic** [comment]
@igr jel ovo malo bolje http://os.petlja.org/vi/? :)

**Comment by igr** [comment]
@teosarkic značajno bolje i ugodinije!

**Comment by teosarkic** [comment]
Evo i novog izgleda BubbleBee-ja http://petlja.org/BubbleBee

**Comment by igr** [comment]
Meni je ovo odlično.
