### ISSUE TITLE
Promeniti bold boju na /About

### ISSUE THREAD

**Issue by igr** [Petlja/bugs-and-improvements#29]
Možda grešim, ali mi se čini da su ove dve boje iste - ili bar slično zelene - pa ne znam kada mogu da kliknem a kada ne. Na primer, da li su ovo linkovi ili ne: http://petlja.org/About A ovde: http://petlja.org/?

**Comment by delta003** [comment]
Na /About nisu linkovi. Hvala na predlogu! Promenicemo bold boju.
