### ISSUE TITLE
Postaviti link ka "Prijava baga / zahtev za funkcionalnost"

### ISSUE THREAD

**Issue by teosarkic** [Petlja/bugs-and-improvements#3]
Link ka https://github.com/Petlja/bugs-and-improvements/issues/ postaviti u footer petlja.org i takprog.petlja.org

**Comment by teosarkic** [comment]
Dodati i link ka GitHub-u, odakle ce ljudi kasnije moci da skinu kod ako zele da doprinesu projektu https://github.com/Petlja/

**Comment by DuXXuD** [comment]
Done.
