### ISSUE TITLE
Ne radi promena lozinke

### ISSUE THREAD

**Issue by igr** [Petlja/bugs-and-improvements#30]
![image](https://cloud.githubusercontent.com/assets/2280001/25784298/9208f35e-336a-11e7-991d-7e2c0778a801.png)

**Comment by delta003** [comment]
@igr Verovatno je istekao poslati token ili je u medjuvremenu generisan drugi (vise puta zahtevan reset). Da li ste uspeli da resetujete u medjuvremenu? Probajte da zahtevate novi reset, pa ako se ponovi problem pisite.
