### ISSUE TITLE
Problem tokom promene avatara

### ISSUE THREAD

**Issue by mlosh** [Petlja/bugs-and-improvements#32]
Odredjene slike mogu, bez obzira na rezoluciju i format, a odredjene ne mogu da se uploaduju na http://bubblebee.petlja.org/nalog/izmena.

**Comment by delta003** [comment]
bubblebee.petlja.org se izbacuje iz upotrebe. Uskoro cemo omoguciti promenu avatara na petlja.org/cpanel
