### ISSUE TITLE
Pogresan link u okviru lekcije 17. za Python (Osnovna skola)

### ISSUE THREAD

**Issue by MarVelNS** [Petlja/bugs-and-improvements#33]
Postovani,
U okviru lekcije 17 za ucenje Python-a za VI razred osnovne skole, stavke Prirucnik i Prirucnik 2.deo obe vode na isti dokument - http://bubblebee.petlja.org/Media/Default/Programiraj/VI/18.lekcija%20-%20Python%20igra%20Kaladont/Prirucnik%20za%20ucenike-Python%20igra%20Kaladont%20I%20deo-VI%20razred.pdf
Molim Vas da ispravite gresku i okacite odgovarajuci dokument za stavku Prirucnik 2. deo.
Hvala.

**Comment by delta003** [comment]
Premesteno.
