### ISSUE TITLE
Dodati footer na petlja i takprog.petlja

### ISSUE THREAD

**Issue by teosarkic** [Petlja/bugs-and-improvements#4]
Primer sa HackerRank-a:

![image](https://cloud.githubusercontent.com/assets/1322239/22345140/36390696-e3ff-11e6-84ef-fab0d7b9925d.png)

**Comment by DuXXuD** [comment]
Ubaciti linkove:

BubbleBee - http://bubblebee.petlja.org
Takprog - http://takprog.petlja.org
BubbleCup - http://www.bubblecup.org/
Dabar - http://dabar.edu.rs/
GitHub - https://github.com/Petlja/
Facebook - https://www.facebook.com/BubbleBeeProg/
Prijavi grešku / Predloži funkcionalnost - https://github.com/Petlja/bugs-and-improvements/issues/

Ubaciti kad bude gotovo:
FAQ
O nama
Blog/Forum
Kalendar takmicenja
Prikljuci se - (kako se prikljuciti Petlji)

**Comment by delta003** [comment]
Done

**Comment by teosarkic** [comment]
Napravih za ovaj preostali deo novi task na internoj listi.
