### ISSUE TITLE
Raw exceptions prilikom registracije na petlja.org

### ISSUE THREAD

**Issue by DuXXuD** [Petlja/bugs-and-improvements#5]
npr ispisuje:
RegistrationNotValid
UserNameEmailNotUnique

Ispraviti u neki opis, pogotovo kada username postoji uputiti ih na objasnjenje da je moguce da vec imaju account na BubbleBee koji sada vazi i za Petlju.

**Comment by srdjan-bozovic** [comment]
Uradjeno
