### ISSUE TITLE
Nevalidan anti-forgery token nakon logovanja na BubbleBee

### ISSUE THREAD

**Issue by dd0** [Petlja/bugs-and-improvements#7]
Nakon logovanja u BubbleBee (logovan na Petlju, pa klik na ime koji vodi na bubblebee.petlja.org/nalog/pregled traži BubbleBee login), dobijam veoma detaljnu poruku o grešci - nevalidan anti-forgery token.

Copy/paste stranice sa porukom o grešci:

> Server Error in '/' Application.
> The provided anti-forgery token was meant for a different claims-based user than the current user.
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.
> 
> Exception Details: System.Web.Mvc.HttpAntiForgeryException: The provided anti-forgery token was meant for a different claims-based user than the current user.
> 
> Source Error:
> 
> An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
> 
> Stack Trace:
> 
> 
> [HttpAntiForgeryException (0x80004005): The provided anti-forgery token was meant for a different claims-based user than the current user.]
>    System.Web.Helpers.AntiXsrf.TokenValidator.ValidateTokens(HttpContextBase httpContext, IIdentity identity, AntiForgeryToken sessionToken, AntiForgeryToken fieldToken) +860
>    System.Web.Helpers.AntiXsrf.AntiForgeryWorker.Validate(HttpContextBase httpContext) +119
>    Orchard.Mvc.AntiForgery.AntiForgeryAuthorizationFilter.OnAuthorization(AuthorizationContext filterContext) +177
>    System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor) +157
>    System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName) +663
>    System.Web.Mvc.<>c__DisplayClass1d.<BeginExecuteCore>b__19() +39
>    System.Web.Mvc.Async.<>c__DisplayClass1.<MakeVoidDelegate>b__0() +22
>    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
>    System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +22
>    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
>    System.Web.Mvc.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult) +42
>    System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +22
>    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
>    Orchard.Mvc.Routes.HttpAsyncHandler.EndProcessRequest(IAsyncResult result) +42
>    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +657
>    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +146
> 
> 
> Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1590.0 

Inače, u source ove stranice piše ovo :)

> This error page might contain sensitive information because ASP.NET is configured to show verbose error messages using &lt;customErrors mode="Off"/&gt;. Consider using &lt;customErrors mode="On"/&gt; or &lt;customErrors mode="RemoteOnly"/&gt; in production environments.-->

**Comment by delta003** [comment]
Nije problem u tokenu. petlja.org ima bug prilikom login-a. Korisnik koji se uloguje na petlja.org uopste nije ulogovan na bubblebee i na takprog. 
Greska je u postavljanju domena za cookie. Postavlja se `petlja.org` umesto `.petlja.org`.
Quick fix :)

**Comment by srdjan-bozovic** [comment]
Popravljeno
