### ISSUE TITLE
Uslovi za username

### ISSUE THREAD

**Issue by delta003** [Petlja/bugs-and-improvements#9]
- Minimalno karaktera? Sad sam video username dd
- Da li imamo uslove za karaktere iz [a-zA-Z0-9_-]?

**Comment by srdjan-bozovic** [comment]
Ne, na bubblebee nije bilo takvih uslova. Predlozi dobrodosli :)

**Comment by delta003** [comment]
Dogovorili smo se da regex bude [a-zA-Z0-9_]+, treba ovo sto pre dodati zato sto se ljudi registruju sa tackom

**Comment by delta003** [comment]
Pratimo u drugom repou
